name: release

on:
  push:
    tags: [ v* ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck
      - name: Pack
        run: npm pack
      - name: Release
        uses: ./
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            *.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
